
package com.monk.util.webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceDemoServer", targetNamespace = "http://webService.util.monk.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceDemoServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getString", targetNamespace = "http://webService.util.monk.com/", className = "com.monk.util.webService.client.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://webService.util.monk.com/", className = "com.monk.util.webService.client.GetStringResponse")
    @Action(input = "http://webService.util.monk.com/WebServiceDemoServer/getStringRequest", output = "http://webService.util.monk.com/WebServiceDemoServer/getStringResponse")
    public String getString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
