
package com.monk.util.webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceDemoServerService", targetNamespace = "http://webService.util.monk.com/", wsdlLocation = "http://0.0.0.0:9734/WebServiceDemo?wsdl")
public class WebServiceDemoServerService
    extends Service
{

    private final static URL WEBSERVICEDEMOSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEDEMOSERVERSERVICE_EXCEPTION;
    private final static QName WEBSERVICEDEMOSERVERSERVICE_QNAME = new QName("http://webService.util.monk.com/", "WebServiceDemoServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0:9734/WebServiceDemo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEDEMOSERVERSERVICE_WSDL_LOCATION = url;
        WEBSERVICEDEMOSERVERSERVICE_EXCEPTION = e;
    }

    public WebServiceDemoServerService() {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVERSERVICE_QNAME);
    }

    public WebServiceDemoServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVERSERVICE_QNAME, features);
    }

    public WebServiceDemoServerService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEDEMOSERVERSERVICE_QNAME);
    }

    public WebServiceDemoServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEDEMOSERVERSERVICE_QNAME, features);
    }

    public WebServiceDemoServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDemoServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceDemoServer
     */
    @WebEndpoint(name = "WebServiceDemoServerPort")
    public WebServiceDemoServer getWebServiceDemoServerPort() {
        return super.getPort(new QName("http://webService.util.monk.com/", "WebServiceDemoServerPort"), WebServiceDemoServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceDemoServer
     */
    @WebEndpoint(name = "WebServiceDemoServerPort")
    public WebServiceDemoServer getWebServiceDemoServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.util.monk.com/", "WebServiceDemoServerPort"), WebServiceDemoServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEDEMOSERVERSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEDEMOSERVERSERVICE_EXCEPTION;
        }
        return WEBSERVICEDEMOSERVERSERVICE_WSDL_LOCATION;
    }

}
